name = "kyle"
main = "src/index.ts"
compatibility_date = "2025-09-18"
compatibility_flags = [ "nodejs_compat" ]

[observability]
enabled = true

# Environment variables (non-sensitive)
[vars]
# Add any non-sensitive variables here if needed
RADARR_HOST = "https://jasonvh.rigel.usbx.me/radarr"
SONARR_HOST = "https://jasonvh.rigel.usbx.me/sonarr"
ULTRA_HOST = "https://jasonvh.rigel.usbx.me/ultra-api"